[workspace]
resolver = "3"
members = [
    "app/aurascan",
    "crates/burn-3ddfa",
    "crates/gst-plugin-aurascan",
    "crates/matio",
    "crates/matio-sys",
    "crates/scrfd-burn",
    "crates/sixdrepnet360-burn",
]

[workspace.dependencies]
burn = "0.21.0"
resnet-burn = { git = "https://github.com/tracel-ai/models", package = "resnet-burn", default-features = false, features = ["pretrained"] }
mobilenetv2-burn = { git = "https://github.com/tracel-ai/models", package = "mobilenetv2-burn", default-features = false }
scrfd-burn.path = "crates/scrfd-burn"
sixdrepnet360-burn.path = "crates/sixdrepnet360-burn"

edgefirst-tracker = "0.24"

eyre = "0.6.12"
nokhwa = "0.10.11"
byte-slice-cast = "1"

nalgebra = "0.35"
lapjv = "0.3"

adw = { package = "libadwaita", version = "0.9.1" }
gst = { package = "gstreamer", version = "0.25" }
gst-analytics = { package = "gstreamer-analytics", version = "0.25" }
gst-app = { package = "gstreamer-app", version = "0.25" }
gst-base = { package = "gstreamer-base", version = "0.25" }
gst-plugin-aurascan.path = "crates/gst-plugin-aurascan"
gst-plugin-gtk4 = "0.15.2"
gst-plugin-version-helper = "0.8.4"
gst-video = { package = "gstreamer-video", version = "0.25" }
gtk = { package = "gtk4", version = "0.11.3" }
relm4 = "0.11"
relm4-components = "0.11"

# Local dependencies
burn-3ddfa.path = "crates/burn-3ddfa"
bytetrack.path = "crates/bytetrack"
matio.path = "crates/matio"
matio-sys.path = "crates/matio-sys"

[patch.crates-io]
cubecl-hip-sys.path = "../cubecl-hip-sys/crates/cubecl-hip-sys"

[profile.release]
debug = true
strip = false
