[workspace]
resolver = "3"
members = [
    "crates/aurascan-faceselector",
    "crates/aurascan-gtk4",
    "crates/aurascan-headposeview",
    "crates/aurascan-oneeurofilter",
    "crates/aurascan-smoothedcrop",
    "crates/aurascan-steam",
    "crates/burn-3ddfa",
    "crates/epoxy-sys",
    "crates/gst-plugin-aurascan",
    "crates/matio",
    "crates/matio-sys",
    "crates/scrfd-burn",
    "crates/sixdrepnet360-burn",
]

[workspace.dependencies]
adw = { package = "libadwaita", version = "0.9.1", features = ["v1_5"] }
async-channel = "2.5"
burn = "0.21.0"
burn-store = { version = "0.21.0", features = ["std", "pytorch"] }
bytemuck = "1.25"
byte-slice-cast = "1"
edgefirst-tracker = "0.24"
eyre = "0.6.12"
dirs = "6.0.0"
futures-channel = "0.3"
glam = "0.33"
glib = { version = "0.22", features = ["v2_68"] }
glow = "0.17"
gst = { package = "gstreamer", version = "0.25", features = ["v1_28"] }
gst-analytics = { package = "gstreamer-analytics", version = "0.25", features = ["v1_28"] }
gst-app = { package = "gstreamer-app", version = "0.25" }
gst-base = { package = "gstreamer-base", version = "0.25", features = ["v1_28"] }
gst-plugin-aurascan.path = "crates/gst-plugin-aurascan"
gst-plugin-gtk4 = "0.15.2"
gst-plugin-version-helper = "0.8.4"
gst-video = { package = "gstreamer-video", version = "0.25", features = ["v1_28"] }
gtk = { package = "gtk4", version = "0.11.3", features = ["v4_16"] }
keyvalues-serde = "0.2"
log = "0.4"
opencv = { version = "0.99", features = ["clang-runtime"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing-subscriber = "0.3"
wgpu = "29.0"
zerocopy = { version = "0.8", features = ["derive"] }

# Local dependencies
aurascan-faceselector.path = "crates/aurascan-faceselector"
aurascan-gtk4.path = "crates/aurascan-gtk4"
aurascan-headposeview.path = "crates/aurascan-headposeview"
aurascan-smoothedcrop.path = "crates/aurascan-smoothedcrop"
aurascan-steam.path = "crates/aurascan-steam"
burn-3ddfa.path = "crates/burn-3ddfa"
bytetrack.path = "crates/bytetrack"
epoxy-sys.path = "crates/epoxy-sys"
matio.path = "crates/matio"
matio-sys.path = "crates/matio-sys"
scrfd-burn.path = "crates/scrfd-burn"
sixdrepnet360-burn.path = "crates/sixdrepnet360-burn"

[package]
name = "aurascan"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { workspace = true, features = ["v1_4"] }
aurascan-gtk4.workspace = true
aurascan-steam.workspace = true
epoxy-sys.workspace = true
eyre.workspace = true
gtk.workspace = true
glib.workspace = true
glow.workspace = true
gst-analytics.workspace = true
gst-plugin-gtk4.workspace = true
gst-plugin-aurascan = { workspace = true, features = ["scrfd-embedded", "sixdrepnet360-pretrained", "vulkan", "rocm"] }
gst.workspace = true
gst-app.workspace = true
gst-video.workspace = true
log.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true

[patch.crates-io]
cubecl-hip-sys.path = "../cubecl-hip-sys/crates/cubecl-hip-sys"

[profile.release]
debug = true
strip = false
