[workspace]
resolver = "3"
members = [
    "crates/aurascan-headposeview",
    "crates/burn-3ddfa",
    "crates/epoxy-sys",
    "crates/gst-plugin-aurascan",
    "crates/matio",
    "crates/matio-sys",
    "crates/scrfd-burn",
    "crates/sixdrepnet360-burn",
]

[workspace.dependencies]
burn = "0.21.0"
burn-store = { version = "0.21.0", features = ["std", "pytorch"] }
dirs = "6.0.0"

edgefirst-tracker = "0.24"

eyre = "0.6.12"
nokhwa = "0.10.11"
byte-slice-cast = "1"

nalgebra = "0.35"
lapjv = "0.3"

adw = { package = "libadwaita", version = "0.9.1" }
bytemuck = "1.25"
glam = "0.33"
glow = "0.17"
gst = { package = "gstreamer", version = "0.25" }
gst-analytics = { package = "gstreamer-analytics", version = "0.25" }
gst-app = { package = "gstreamer-app", version = "0.25" }
gst-base = { package = "gstreamer-base", version = "0.25" }
gst-plugin-aurascan.path = "crates/gst-plugin-aurascan"
gst-plugin-gtk4 = "0.15.2"
gst-plugin-version-helper = "0.8.4"
gst-video = { package = "gstreamer-video", version = "0.25" }
gtk = { package = "gtk4", version = "0.11.3" }
relm4 = "0.11"
relm4-components = "0.11"
wgpu = "29.0"

# Local dependencies
aurascan-headposeview.path = "crates/aurascan-headposeview"
burn-3ddfa.path = "crates/burn-3ddfa"
bytetrack.path = "crates/bytetrack"
epoxy-sys.path = "crates/epoxy-sys"
matio.path = "crates/matio"
matio-sys.path = "crates/matio-sys"
scrfd-burn.path = "crates/scrfd-burn"
sixdrepnet360-burn.path = "crates/sixdrepnet360-burn"

[package]
name = "aurascan"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { workspace = true, features = ["v1_4"] }
aurascan-headposeview.workspace = true
epoxy-sys.workspace = true
eyre.workspace = true
gtk = { workspace = true, features = ["v4_8"] }
glow.workspace = true
gst-analytics = { workspace = true, features = ["v1_28"] }
gst-plugin-gtk4.workspace = true
gst-plugin-aurascan = { workspace = true, features = ["scrfd-embedded", "sixdrepnet360-pretrained", "vulkan", "rocm"] }
gst.workspace = true
gst-app.workspace = true
gst-video.workspace = true
relm4 = { workspace = true, features = ["libadwaita"] }
relm4-components.workspace = true
wgpu.workspace = true

[patch.crates-io]
cubecl-hip-sys.path = "../cubecl-hip-sys/crates/cubecl-hip-sys"

[profile.release]
debug = true
strip = false
