[workspace]
authors = ["Jean-Pierre De Jesus DIAZ <me@jeandudey.tech>"]
channels = ["conda-forge"]
name = "aurascan"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"

[pypi-dependencies]
sixdrepnet360 = { git = "https://github.com/jeandudey/pytorch-sixdrepnet360/", branch = "master", extras = ["export"] }
