load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain", "system_python_wheel_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@toolchains//bootlin:defs.bzl", "cxx_bootlin_toolchain", "download_bootlin_distribution")
load("@root//autotools:toolchain.bzl", "system_autotools_toolchain")
load("@root//cmake:toolchain.bzl", "cmake_toolchain", "download_cmake_distribution")
load("@root//ninja:toolchain.bzl", "ninja_toolchain", "download_ninja_distribution")
load(":meson.bzl", "system_meson_toolchain")
load(":rust.bzl", "rust_toolchain")

download_bootlin_distribution(
    name = "bootlin",
    arch = "x86-64",
    libc = "glibc",
    version = "stable-2025.08-1",
    visibility = ["PUBLIC"],
)

cxx_bootlin_toolchain(
    name = "cxx",
    distribution = ":bootlin",
    visibility = ["PUBLIC"],
)

# Genrule
system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

# Rust
http_archive(
    name = "rust-1.97.0-x86_64-unknown-linux-gnu.tar.gz",
    urls = ["https://static.rust-lang.org/dist/rust-1.97.0-x86_64-unknown-linux-gnu.tar.gz"],
    sha256 = "eb89b20287153391c49ebcdb7fd91b683a12438d129bfb92eadcc495545af3a7",
    strip_prefix = "rust-1.97.0-x86_64-unknown-linux-gnu",
)

rust_toolchain(
    name = "rust",
    default_edition = "2024",
    distribution = ":rust-1.97.0-x86_64-unknown-linux-gnu.tar.gz",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_wheel_toolchain(
    name = "python_wheel",
    visibility = ["PUBLIC"],
)

# Ninja
download_ninja_distribution(
    name = "ninja-distribution",
    version = "1.13.2",
)

ninja_toolchain(
    name = "ninja",
    distribution = ":ninja-distribution",
    visibility = ["PUBLIC"],
)

# Meson
system_meson_toolchain(
    name = "meson",
    visibility = ["PUBLIC"],
)

# CMake
download_cmake_distribution(
    name = "cmake-distribution",
    version = "4.4.2",
)

cmake_toolchain(
    name = "cmake",
    distribution = ":cmake-distribution",
    visibility = ["PUBLIC"],
)

# Autotools
system_autotools_toolchain(
    name = "autotools",
    visibility = ["PUBLIC"],
)
