load("@prelude//toolchains:python.bzl", "remote_python_toolchain", "system_python_wheel_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@toolchains//bootlin:defs.bzl", "cxx_bootlin_toolchain", "download_bootlin_distribution")

download_bootlin_distribution(
    name = "bootlin",
    arch = "x86-64",
    libc = "glibc",
    version = "stable-2025.08-1",
)

cxx_bootlin_toolchain(
    name = "cxx",
    distribution = ":bootlin",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    default_edition = "2024",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_wheel_toolchain(
    name = "python_wheel",
    visibility = ["PUBLIC"],
)
