[package]
name = "sixdrepnet360-burn"
version = "0.1.0"
edition = "2024"

[features]
pretrained = ["dirs", "burn/network"]

[dependencies]
burn = { version = "0.21.0", features = ["train", "vision"] }
burn-store = { version = "0.21.0", features = ["std", "pytorch"] }
dirs = { version = "6.0.0", optional = true }
