[package]
name = "scrfd-burn"
version = "0.1.0"
edition = "2024"

[[example]]
name = "inference"
required-features = ["example"]

[features]
example = ["embedded", "burn/flex", "burn/vulkan", "burn/rocm", "image", "imageproc"]
embedded = []

[dependencies]
burn = { workspace = true, features = ["train", "vision"] }
burn-store.workspace = true
thiserror.workspace = true
image = { version = "0.25", optional = true }
imageproc = { version = "0.26", optional = true }

[build-dependencies]
burn-onnx.workspace = true
