[package]
name = "gst-plugin-burnextra"
description = "Extra GStreamer plugins using burn"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/jeandudey/burn-experiment"

[lib]
name = "gstburnextra"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = []
vulkan = ["burn/vulkan"]
rocm = ["burn/rocm"]
scrfd-embedded = ["scrfd-burn/embedded"]
sixdrepnet360-pretrained = ["sixdrepnet360-burn/pretrained"]

[dependencies]
burn = { workspace = true, features = ["autotune", "dispatch", "flex", "fusion"] }
byte-slice-cast.workspace = true
edgefirst-tracker.workspace = true
eyre.workspace = true
gst = { workspace = true, features = ["v1_28"] }
gst-analytics = { workspace = true, features = ["v1_28"] }
gst-base = { workspace = true, features = ["v1_28"] }
gst-video = { workspace = true, features = ["v1_28"] }
scrfd-burn.workspace = true
sixdrepnet360-burn.workspace = true

[build-dependencies]
gst-plugin-version-helper.workspace = true

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-video-1.0, gstreamer-analytics-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
