[package]
name = "webcam"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true

relm4 = { workspace = true, features = ["libadwaita"] }
adw = { workspace = true, features = ["v1_4"] }
gtk = { workspace = true, features = ["v4_8"] }
gst-analytics = { workspace = true, features = ["v1_28"] }
gst-plugin-gtk4.workspace = true
gst-plugin-burnextra = { workspace = true, features = ["scrfd-embedded", "sixdrepnet360-pretrained", "vulkan", "rocm"] }
gst.workspace = true
gst-app.workspace = true
gst-video.workspace = true

thiserror = "2.0.18"
image = "0.25.10"
crossbeam-channel = "0.5.15"
async-channel = "2.5.0"
