[package]
name = "webcam"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
burn = { workspace = true, features = ["dispatch", "flex", "rocm", "vulkan", "wgpu"] }
sixdrepnet360-burn = { workspace = true, features = ["pretrained"] }
scrfd-burn = { workspace = true }
gtk = { workspace = true, features = ["v4_8"] }
gst-plugin-gtk4.workspace = true
gst.workspace = true
gst-app.workspace = true
gst-video.workspace = true
thiserror = "2.0.18"
image = "0.25.10"
crossbeam-channel = "0.5.15"
async-channel = "2.5.0"
